# coding: utf-8

# flake8: noqa
"""
    OriginStamp Documentation

    <br/>The following documentation describes the API v3 for OriginStamp. With this documentation you are able to try out the different requests and see the responses. For the authorization, add your API key to the Authorization header of your request.<br/><h2>Invoice</h2><p>The invoice is based on your individual usage. The following table illustrates the request types, that are billed in credits.</p><table><tr><th>Request Type</th><th>Condition</th><th>Credits</th><tr><td style='border-bottom-style:solid; border-color: #c0c0c0;'></td><tr><th>Submission</th><th>create timestamp</th><th>1 Credit</th><tr><th>Submission</th><th>timestamp already exists</th><th>0.3 Credits</th><tr><th>Status</th><th>no timestamp information available</th><th>0.1 Credit</th><tr><th>Status</th><th>timestamp information</th><th>0.3 Credits</th><tr><th>Proof</th><th>no proof available</th><th>0.1 Credits</th><tr><th>Proof</th><th>merkle tree as proof</th><th>3 Credits</th><tr><th>Proof</th><th>seed as proof</th><th>3 Credits</th><tr><th>Proof</th><th>PDF Certificate</th><th>5 Credits</th><tr><th>Notification</th><th>webhook notification</th><th>1.5 Credits</th><tr><th>Notification</th><th>mail notification</th><th>5 Credits</th><tr><th>Notification</th><th>trigger webhook</th><th>5 0.3</th></table><br/><h2>Common Problems</h2><ul><li>Make sure you set the Authorization with your API key</li><li>If a cloudflare error occurs, please set a custom UserAgent header.</li><li>Please have a look at the models below to find out what each field means.</li></ul>  # noqa: E501

    OpenAPI spec version: 3.0
    Contact: mail@originstamp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from originstamp_client.models.default_scheduler_response import DefaultSchedulerResponse
from originstamp_client.models.default_timestamp_response import DefaultTimestampResponse
from originstamp_client.models.default_usage_response import DefaultUsageResponse
from originstamp_client.models.defaultstring import Defaultstring
from originstamp_client.models.notification import Notification
from originstamp_client.models.proof_request import ProofRequest
from originstamp_client.models.response_entity import ResponseEntity
from originstamp_client.models.scheduler_request import SchedulerRequest
from originstamp_client.models.scheduler_response import SchedulerResponse
from originstamp_client.models.timestamp_data import TimestampData
from originstamp_client.models.timestamp_request import TimestampRequest
from originstamp_client.models.timestamp_response import TimestampResponse
from originstamp_client.models.usage_response import UsageResponse
from originstamp_client.models.webhook_request import WebhookRequest
