# coding: utf-8

"""
    OriginStamp Client

    OpenAPI spec version: 3.0
    OriginStamp Documentation: https://docs.originstamp.com
    Contact: mail@originstamp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class CurrencyModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'currency': 'str',
        'currency_id': 'int'
    }

    attribute_map = {
        'currency': 'currency',
        'currency_id': 'currency_id'
    }

    def __init__(self, currency=None, currency_id=None):  # noqa: E501
        """CurrencyModel - a model defined in Swagger"""  # noqa: E501

        self._currency = None
        self._currency_id = None
        self.discriminator = None

        if currency is not None:
            self.currency = currency
        if currency_id is not None:
            self.currency_id = currency_id

    @property
    def currency(self):
        """Gets the currency of this CurrencyModel.  # noqa: E501

        Name of the currency (uppercase)  # noqa: E501

        :return: The currency of this CurrencyModel.  # noqa: E501
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency):
        """Sets the currency of this CurrencyModel.

        Name of the currency (uppercase)  # noqa: E501

        :param currency: The currency of this CurrencyModel.  # noqa: E501
        :type: str
        """

        self._currency = currency

    @property
    def currency_id(self):
        """Gets the currency_id of this CurrencyModel.  # noqa: E501

        ID of the currency, e.g. 0: Bitcoin 1: Ethereum  # noqa: E501

        :return: The currency_id of this CurrencyModel.  # noqa: E501
        :rtype: int
        """
        return self._currency_id

    @currency_id.setter
    def currency_id(self, currency_id):
        """Sets the currency_id of this CurrencyModel.

        ID of the currency, e.g. 0: Bitcoin 1: Ethereum  # noqa: E501

        :param currency_id: The currency_id of this CurrencyModel.  # noqa: E501
        :type: int
        """

        self._currency_id = currency_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CurrencyModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CurrencyModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
