# coding: utf-8

"""
    OriginStamp Client

    OpenAPI spec version: 3.0
    OriginStamp Documentation: https://docs.originstamp.com
    Contact: mail@originstamp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class DownloadLinkResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'download_url': 'str',
        'file_name': 'str',
        'file_size_bytes': 'int'
    }

    attribute_map = {
        'download_url': 'download_url',
        'file_name': 'file_name',
        'file_size_bytes': 'file_size_bytes'
    }

    def __init__(self, download_url=None, file_name=None, file_size_bytes=None):  # noqa: E501
        """DownloadLinkResponse - a model defined in Swagger"""  # noqa: E501

        self._download_url = None
        self._file_name = None
        self._file_size_bytes = None
        self.discriminator = None

        if download_url is not None:
            self.download_url = download_url
        if file_name is not None:
            self.file_name = file_name
        if file_size_bytes is not None:
            self.file_size_bytes = file_size_bytes

    @property
    def download_url(self):
        """Gets the download_url of this DownloadLinkResponse.  # noqa: E501

        URL to download file.  # noqa: E501

        :return: The download_url of this DownloadLinkResponse.  # noqa: E501
        :rtype: str
        """
        return self._download_url

    @download_url.setter
    def download_url(self, download_url):
        """Sets the download_url of this DownloadLinkResponse.

        URL to download file.  # noqa: E501

        :param download_url: The download_url of this DownloadLinkResponse.  # noqa: E501
        :type: str
        """

        self._download_url = download_url

    @property
    def file_name(self):
        """Gets the file_name of this DownloadLinkResponse.  # noqa: E501

        File name of downloaded file.  # noqa: E501

        :return: The file_name of this DownloadLinkResponse.  # noqa: E501
        :rtype: str
        """
        return self._file_name

    @file_name.setter
    def file_name(self, file_name):
        """Sets the file_name of this DownloadLinkResponse.

        File name of downloaded file.  # noqa: E501

        :param file_name: The file_name of this DownloadLinkResponse.  # noqa: E501
        :type: str
        """

        self._file_name = file_name

    @property
    def file_size_bytes(self):
        """Gets the file_size_bytes of this DownloadLinkResponse.  # noqa: E501

        File size in bytes.  # noqa: E501

        :return: The file_size_bytes of this DownloadLinkResponse.  # noqa: E501
        :rtype: int
        """
        return self._file_size_bytes

    @file_size_bytes.setter
    def file_size_bytes(self, file_size_bytes):
        """Sets the file_size_bytes of this DownloadLinkResponse.

        File size in bytes.  # noqa: E501

        :param file_size_bytes: The file_size_bytes of this DownloadLinkResponse.  # noqa: E501
        :type: int
        """

        self._file_size_bytes = file_size_bytes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DownloadLinkResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DownloadLinkResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
