# coding: utf-8

"""
    OriginStamp Client

    OpenAPI spec version: 3.0
    OriginStamp Documentation: https://docs.originstamp.com
    Contact: mail@originstamp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class UsageResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'certificate_per_month': 'int',
        'consumed_certificates': 'int',
        'consumed_credits': 'float',
        'consumed_timestamps': 'int',
        'credits_per_month': 'float',
        'limitation_type': 'int',
        'remaining_credits': 'float',
        'timestamps_per_month': 'int'
    }

    attribute_map = {
        'certificate_per_month': 'certificate_per_month',
        'consumed_certificates': 'consumed_certificates',
        'consumed_credits': 'consumed_credits',
        'consumed_timestamps': 'consumed_timestamps',
        'credits_per_month': 'credits_per_month',
        'limitation_type': 'limitation_type',
        'remaining_credits': 'remaining_credits',
        'timestamps_per_month': 'timestamps_per_month'
    }

    def __init__(self, certificate_per_month=None, consumed_certificates=None, consumed_credits=None, consumed_timestamps=None, credits_per_month=None, limitation_type=None, remaining_credits=None, timestamps_per_month=None):  # noqa: E501
        """UsageResponse - a model defined in Swagger"""  # noqa: E501

        self._certificate_per_month = None
        self._consumed_certificates = None
        self._consumed_credits = None
        self._consumed_timestamps = None
        self._credits_per_month = None
        self._limitation_type = None
        self._remaining_credits = None
        self._timestamps_per_month = None
        self.discriminator = None

        if certificate_per_month is not None:
            self.certificate_per_month = certificate_per_month
        if consumed_certificates is not None:
            self.consumed_certificates = consumed_certificates
        if consumed_credits is not None:
            self.consumed_credits = consumed_credits
        if consumed_timestamps is not None:
            self.consumed_timestamps = consumed_timestamps
        if credits_per_month is not None:
            self.credits_per_month = credits_per_month
        if limitation_type is not None:
            self.limitation_type = limitation_type
        if remaining_credits is not None:
            self.remaining_credits = remaining_credits
        if timestamps_per_month is not None:
            self.timestamps_per_month = timestamps_per_month

    @property
    def certificate_per_month(self):
        """Gets the certificate_per_month of this UsageResponse.  # noqa: E501

        Total number of certificates available per month.  # noqa: E501

        :return: The certificate_per_month of this UsageResponse.  # noqa: E501
        :rtype: int
        """
        return self._certificate_per_month

    @certificate_per_month.setter
    def certificate_per_month(self, certificate_per_month):
        """Sets the certificate_per_month of this UsageResponse.

        Total number of certificates available per month.  # noqa: E501

        :param certificate_per_month: The certificate_per_month of this UsageResponse.  # noqa: E501
        :type: int
        """

        self._certificate_per_month = certificate_per_month

    @property
    def consumed_certificates(self):
        """Gets the consumed_certificates of this UsageResponse.  # noqa: E501

        Number of certificates requested for the current month.  # noqa: E501

        :return: The consumed_certificates of this UsageResponse.  # noqa: E501
        :rtype: int
        """
        return self._consumed_certificates

    @consumed_certificates.setter
    def consumed_certificates(self, consumed_certificates):
        """Sets the consumed_certificates of this UsageResponse.

        Number of certificates requested for the current month.  # noqa: E501

        :param consumed_certificates: The consumed_certificates of this UsageResponse.  # noqa: E501
        :type: int
        """

        self._consumed_certificates = consumed_certificates

    @property
    def consumed_credits(self):
        """Gets the consumed_credits of this UsageResponse.  # noqa: E501

        Number of used credits for the current month.  # noqa: E501

        :return: The consumed_credits of this UsageResponse.  # noqa: E501
        :rtype: float
        """
        return self._consumed_credits

    @consumed_credits.setter
    def consumed_credits(self, consumed_credits):
        """Sets the consumed_credits of this UsageResponse.

        Number of used credits for the current month.  # noqa: E501

        :param consumed_credits: The consumed_credits of this UsageResponse.  # noqa: E501
        :type: float
        """

        self._consumed_credits = consumed_credits

    @property
    def consumed_timestamps(self):
        """Gets the consumed_timestamps of this UsageResponse.  # noqa: E501

        Number of timestamps created for the current month.  # noqa: E501

        :return: The consumed_timestamps of this UsageResponse.  # noqa: E501
        :rtype: int
        """
        return self._consumed_timestamps

    @consumed_timestamps.setter
    def consumed_timestamps(self, consumed_timestamps):
        """Sets the consumed_timestamps of this UsageResponse.

        Number of timestamps created for the current month.  # noqa: E501

        :param consumed_timestamps: The consumed_timestamps of this UsageResponse.  # noqa: E501
        :type: int
        """

        self._consumed_timestamps = consumed_timestamps

    @property
    def credits_per_month(self):
        """Gets the credits_per_month of this UsageResponse.  # noqa: E501

        Represents the total number of credits per month.  # noqa: E501

        :return: The credits_per_month of this UsageResponse.  # noqa: E501
        :rtype: float
        """
        return self._credits_per_month

    @credits_per_month.setter
    def credits_per_month(self, credits_per_month):
        """Sets the credits_per_month of this UsageResponse.

        Represents the total number of credits per month.  # noqa: E501

        :param credits_per_month: The credits_per_month of this UsageResponse.  # noqa: E501
        :type: float
        """

        self._credits_per_month = credits_per_month

    @property
    def limitation_type(self):
        """Gets the limitation_type of this UsageResponse.  # noqa: E501

        Determines which usage metric is applied (0 = credits, 1 = timestamps).  # noqa: E501

        :return: The limitation_type of this UsageResponse.  # noqa: E501
        :rtype: int
        """
        return self._limitation_type

    @limitation_type.setter
    def limitation_type(self, limitation_type):
        """Sets the limitation_type of this UsageResponse.

        Determines which usage metric is applied (0 = credits, 1 = timestamps).  # noqa: E501

        :param limitation_type: The limitation_type of this UsageResponse.  # noqa: E501
        :type: int
        """

        self._limitation_type = limitation_type

    @property
    def remaining_credits(self):
        """Gets the remaining_credits of this UsageResponse.  # noqa: E501

        Remaining number of credits for the current month.  # noqa: E501

        :return: The remaining_credits of this UsageResponse.  # noqa: E501
        :rtype: float
        """
        return self._remaining_credits

    @remaining_credits.setter
    def remaining_credits(self, remaining_credits):
        """Sets the remaining_credits of this UsageResponse.

        Remaining number of credits for the current month.  # noqa: E501

        :param remaining_credits: The remaining_credits of this UsageResponse.  # noqa: E501
        :type: float
        """

        self._remaining_credits = remaining_credits

    @property
    def timestamps_per_month(self):
        """Gets the timestamps_per_month of this UsageResponse.  # noqa: E501

        Total number of timestamps available per month.  # noqa: E501

        :return: The timestamps_per_month of this UsageResponse.  # noqa: E501
        :rtype: int
        """
        return self._timestamps_per_month

    @timestamps_per_month.setter
    def timestamps_per_month(self, timestamps_per_month):
        """Sets the timestamps_per_month of this UsageResponse.

        Total number of timestamps available per month.  # noqa: E501

        :param timestamps_per_month: The timestamps_per_month of this UsageResponse.  # noqa: E501
        :type: int
        """

        self._timestamps_per_month = timestamps_per_month

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UsageResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UsageResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
